use serde::{Serialize, Deserialize};
use chrono::NaiveDate;
use sqlx::FromRow;

#[derive(Debug, Serialize, Deserialize, Clone, FromRow)]
pub struct Student {
    pub id: i32, // Assuming id is an integer, generated by the database
    pub name: String,
    pub surname: String,
    pub phonenumber: String,
    pub birthday: NaiveDate,
    pub email: String,
}

// We might also want a struct for creating a new student, without the id
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct CreateStudent {
    pub name: String,
    pub surname: String,
    pub phonenumber: String,
    pub birthday: NaiveDate,
    pub email: String,
}
