name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://user:pass@host/db

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: '1.78.0'
        profile: minimal
        override: true
    - name: Install sqlx-cli
      run: cargo install sqlx-cli --version "0.7.4" --locked
    - name: Prepare SQLx data
      run: SQLX_OFFLINE=true cargo sqlx prepare
      env:
        DATABASE_URL: postgres://user:pass@localhost/db
        SQLX_OFFLINE: true
    - name: Build
      run: SQLX_OFFLINE=true cargo build --verbose
      env:
        DATABASE_URL: postgres://user:pass@localhost/db
        SQLX_OFFLINE: true
    - name: Run tests
      run: SQLX_OFFLINE=true cargo test --verbose
      env:
        DATABASE_URL: postgres://user:pass@localhost/db
        SQLX_OFFLINE: true
